@startuml
前端 -> 旺铺后台: 实例化商品数据
旺铺后台 -> 运营平台: 传入商品context
运营平台 -> 旺铺后台: 获取基础主图和视频帧
运营平台 -> 行业持久化端: 获取行业定制帧
旺铺后台  --> 运营平台: 返回基础主图和视频帧
行业持久化端 --> 运营平台: 返回行业定制帧
运营平台 -> diamond: 获取插帧配置
运营平台 --> 前端: 对旺铺和行业返回帧进行前台化表达处理，返回渲染数据
@enduml