@startuml

运营后台 -> 主图空间: 上传主图
运营后台 -> 中台: 增量、存量更新（新增、隐藏、替换）
中台 -> DB: 数据状态HOLD
DB --> 中台: 落库成功
中台 --> 运营后台: 草稿保存成功，平铺预览生效
主图空间 -> 中台: submit，执行主图预发布和正式发布流程
中台 -> ic: 合法性校验，是否落库、ic
ic --> 中台: 落库成功，中台校验状态一致性
中台 --> 运营后台: 发布成功通知
运营后台 -> 详情前台: 前台实时生效、手机预览生效

@enduml