@startuml
(*)  --> "准入商品tag标1837826"
If "查opensearch是否有商品券" then
    If "判断是否有feature标extType:nakedPrice=1，extValue:1" then
    --> [有]"过滤出最多2张商品券，内存态标记出直降券"
        --> "计算直降券券后价"
        --> "渲染直降腰带氛围"
        --> "执行氛围渠道利益点，近N天文案Get"
        --> "领券浮层渲染数据以及自动领券请求参数下发"
        --> (*)
    else
    --> [无]"过滤出最多3张商品券，渲染普通聚划算"
    Endif
-->(*)
else
--> [无] "渲染普通聚划算"
Endif
-->(*)
@enduml