@startuml
(*) --> "sell hsf、正式包发布（知海）"
--> "业务sdk正式包打包（三竺）"
--> "前端资源、模块发布（正寻、天尹）"
--> "astore页面发布（逐翌、無涯）"
--> "apole发布（逐翌、三竺）"
--> "apole灰度配置推送（逐翌、三竺）"
--> "alidetaildecorate发布（逐翌、無涯）"
--> "前端资源版本推送（逐翌、無涯）"
-->(*)
@enduml