@startuml
(*)  --> "多视频管理入口"
If "是否灰度商家" then
--> [是] "解析新扩展结构"
--> "渲染多视频管理内容"
    If "是否勾选mini多视频" then
    --> [是] "公域机审"
        If "机审是否通过" then
        --> [是] "人工审核"
        If "成功返回人工审核分" then
            --> [是] If "是否高于最低标准分" then
                --> [是] "回调提交接口"
                --> "写扩展结构流程"
                -->(*)
                else
                -->(*)
                Endif
            else
            -->(*)
            Endif
        else
        -->(*)
        Endif
    else
    --> "私域机审"
        If "机审是否通过" then
        --> [是]"写扩展结构流程"
        else
        -->(*)
        Endif
    Endif
else
Endif
-->(*)
@enduml