@startuml
(*)  --> "业务总开关判断"
If "是否关闭" then
-->(*)
else
--> If "是否在白名单(分为大促预热/正式/预售/聚划算（单报/双报）)"  then
 --> If "是否在新腰带桶" then
 If "是否下发有新腰带" then
 --> "价格调换（券后价上移，预热价移至当前价）"
 --> (*)
 else
 --> "腰带降级"
 --> (*)
Endif
Endif
@enduml