@startuml
:行业产品B: as Admin
:行业产品A: as Bc
(详情开发) as (Use)

详情产品C -> (评估)

Admin ---> (Use)
Bc ---> (Use)

note right of Admin : 这里临时加个埋点吧
note right of Bc: 这里临时数据从商户拿吧

note right of (Use)
行业产品都和C说了，我还能怎么办？？
end note

note "咱们按照aone来哈" as N2
(评估) .. N2
N2 .. (Use)
@enduml