@startuml
'(*)  --> "check input"
'If "input is verbose" then
'--> [Yes] "turn on verbosity"
'--> "run command"
'else
'--> "run command"
'Endif
'-->(*)
(*) --> "业务评估(人群、优惠、大促叠加)"
--> "功能实现(业务逻辑)"
--> "稳定性评估(长rt，接口性能，接口幂等)"
--> "风险评估(业务风险，稳定性风险，降级、开关、紧急预案)"
--> "代码设计(平台能力沉淀，代码设计)"
--> (*)
@enduml
