@startuml
(*) --> "装修对象实例化"
If "命中类目配置规则" then
    --> [命中类目标+可装修标] "调用行业设置端"
    If "是否有素材投放" then
    --> [有] "透出素材配置和跳转编辑"
    -->(*)
    else
    --> [没有] "透出跳转编辑"
    -->(*)
    EndIf
else
    --> [未命中] "透出开关类配置"
    -->(*)
EndIf
@enduml