@startuml
(*) If "商家是否命中灰度规则" then
--> [是] "主图结构化操作台"
--> "获取基础视频和主图"
--> "调用行业定制图及素材配置"
--> "处理diamond配置化插帧"
--> "组装渲染数据"
--> "调用奥创接口"
--> "下发奥创协议和业务数据"
else
--> "普通商品主图装修"
--> "组装渲染数据"
--> "调用奥创接口"
--> "下发奥创协议和业务数据"
Endif
-->(*)
@enduml