@startuml
(*) If "商家是否有上传更新权限" then
--> [是] "各模块执行submit方法"
--> "视频、图片尺寸、盗图、合规校验"
    --> If "是否校验成功" then
    -->[是] "行业素材配置投放合法校验"
        --> If "是否校验成功" then
        -->[是] "写入features、tags，各模块执行publish方法"
        --> (*)
            else
        --> "禁写提示"
        --> (*)
        Endif
    else
    --> "禁写提示"
    --> (*)
    Endif
else
--> "禁写提示"
Endif
-->(*)
@enduml