@startuml
商家 -> 结构化后台: 1.渲染请求
结构化后台 -> ic: 2.查询扩展结构
ic -> 结构化后台: 3.返回渲染数据
结构化后台 -> 商家: 4.页面渲染（前置机审+算法审结果）

商家 -> 结构化后台: 5.提交请求
结构化后台 -> 视频检查器: 6.提交视频检查
视频检查器 -> 结构化后台: 7.返回检查结果
结构化后台 -> 互动平台: 8.提交需要更新的扩展结构和mini审核流程
结构化后台 -> ic: 9.提交需要更新的扩展结构并更新审核状态
互动平台 --> 结构化后台: 10.消息返回审核成功结果
结构化后台 -> ic: 11.提交需要更新的扩展结构并更新审核状态
@enduml