@startuml
actor client

detail --> ic: 2.商品基本属性初始化请求
client --> detail: 1.无storeId
ic --> detail: 3.返回基本属性
detail --> poi: 4.火凤凰调用storeRelationService获取storeId
poi --> detail: 5.商户返回附近有效门店

client -> detail: 6.有storeId
detail -> ic: 7.第二次发起商品初始化请求
ic -> detail: 8. ic返回商品属性
detail -> ump: 9. 门店优惠查询
ump -> detail: 10. 返回排除非平台优惠

detail -> ipm: 11. 带storeId无areaId
ipm -> detail: 12. 库存返回是否有库存
detail -> ipm: 13. 进行二次查询
ipm -> poi: 14. sku维度调用商户判店
poi -> ipm: 15. 行政区划和经纬度不为空，商户返回门店
ipm -> detail: 16. 返回门店库存到详情
detail -> adp: 17. 透传库存返回结果到物流中心
adp -> detail: 18. 返回时效信息到详情
detail -> client: 19. 详情本地化渲染

@enduml