@startuml
title **malldetailsugar**
actor client
skinparam backgroundColor #EEEBDC
skinparam handwritten false
skinparam sequence {
ArrowColor #000000
ActorBorderColor #000000
LifeLineBorderColor #000000
LifeLineBackgroundColor #A9DCDF
ParticipantBorderColor #000000
ParticipantBackgroundColor #A9DCDF
ParticipantFontName Impact
ParticipantFontSize 15
ActorBackgroundColor #A9DCDF
ActorFontSize 17
}

autonumber "<b> [0]"
client -> Setup: 应用启动
activate Setup
Setup -> 解释引擎: 注册引擎
activate 解释引擎
解释引擎 -> 解释引擎: 注册规则元
解释引擎 -->  Setup: 完成注册
deactivate 解释引擎
Setup -> 业务配置池: 加载业务配置池
activate 业务配置池
业务配置池 -> 业务配置池: 读取配置并转译存储

业务配置池 -> 监听模块: 注册监听器
activate 监听模块
监听模块 --> 业务配置池: 完成注册
deactivate 监听模块
业务配置池 --> Setup: 完成加载
deactivate 业务配置池
Setup --> client: 完成启动
deactivate Setup

activate 监听模块
监听模块 -> 监听模块: 监听配置推送
activate 监听模块
deactivate 监听模块
监听模块 --> 业务配置池: 推送更新配置元数据
deactivate 监听模块

activate 业务配置池
业务配置池 -> 业务配置池: 刷新配置
业务配置池 -> 资源二级缓存池: 刷新资源缓存池
activate 资源二级缓存池
资源二级缓存池 --> 业务配置池: 完成刷新
deactivate 资源二级缓存池
deactivate 业务配置池

client -> Setup: 查询此业务
activate Setup
Setup -> 业务配置池: 获取业务配置
activate 业务配置池
业务配置池 -> 解释引擎: 执行引擎
activate 解释引擎
解释引擎 -> 解释引擎: 规则解释
解释引擎 -> 业务配置池: 规则结果

deactivate 解释引擎
业务配置池 -> 资源二级缓存池: 获取资源
activate 资源二级缓存池
资源二级缓存池 --> 业务配置池: 未命中
资源二级缓存池 ->  资源二级缓存池: 缓存资源转换结果
业务配置池 -> Setup: 返回资源
deactivate 业务配置池
deactivate 资源二级缓存池
Setup -> client: 返回资源

deactivate Setup

@enduml