@startuml
(*)  --> "UMP"
If "XmpItem包含o2oTcgOnlineStoreChannel" then
--> [Y] "门店链路"
    If "ic返回的feature有channelItemId" then
    --> [Y] "门店价"
    --> "其它单品、店铺，跨店排除"
    else
    --> [N] "一口价"
    --> "其它店铺、跨店排除"
    Endif
else
--> [N] "B2C"
Endif
@enduml